project:
  type: website
  output-dir: docs
  
website:
  title: "Tiago Adria Nunes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/tiagoadrianunes/
      - icon: github
        href: https://github.com/TiagoAdriaNunes/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Tiago Adria Nunes"

format:
  html:
    theme: darkly
    toc: true

editor: source

